name: Package

on:
  push:
    branches:
      - master

env:
  HUB: ghcr.io/arugal/alidns-webhook

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: |
          docker build -t ${HUB}/alidns-webhook:0.1.2 .
          docker push ${HUB}/alidns-webhook:0.1.2